// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    // ignore: combinators_ordering
    show
        defaultTargetPlatform,
        kIsWeb,
        TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // ignore: no_default_cases
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz7vVgRfNvjsTATKsBI79uzFT4_psnBnY',
    appId: '1:1056827024268:web:540ede0f11ffd52cb8eca9',
    messagingSenderId: '1056827024268',
    projectId: 'flutter-servisci-app',
    authDomain: 'flutter-servisci-app.firebaseapp.com',
    storageBucket: 'flutter-servisci-app.appspot.com',
    measurementId: 'G-310NB291NL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbEgBEHl6It0yy_QhOZ7483Gy4EhQiWdY',
    appId: '1:1056827024268:android:f1da7591e76c271bb8eca9',
    messagingSenderId: '1056827024268',
    projectId: 'flutter-servisci-app',
    storageBucket: 'flutter-servisci-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLMEwkKWVLbPoEnbUT5RGWQD9Sd0uibxw',
    appId: '1:1056827024268:ios:a90c550e5d566bd2b8eca9',
    messagingSenderId: '1056827024268',
    projectId: 'flutter-servisci-app',
    storageBucket: 'flutter-servisci-app.appspot.com',
    iosBundleId: 'com.example.flutterServisciApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLMEwkKWVLbPoEnbUT5RGWQD9Sd0uibxw',
    appId: '1:1056827024268:ios:4bf3a36a4863af13b8eca9',
    messagingSenderId: '1056827024268',
    projectId: 'flutter-servisci-app',
    storageBucket: 'flutter-servisci-app.appspot.com',
    iosBundleId: 'com.example.flutterServisciApp.RunnerTests',
  );
}
